
// Generated by Together


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * An interface to SAAMS:
 * Refuelling Supervisor Screen:
 * Inputs events from the Refuelling Supervisor, and displays aircraft information.
 * This class is a controller for the AircraftManagementDatabase: sending it messages to change the aircraft status information.
 * This class also registers as an observer of the AircraftManagementDatabase, and is notified whenever any change occurs in that <<model>> element.
 * See written documentation.
 * @stereotype boundary/view/controller
 * @url element://model:project::SAAMS/design:view:::id15rnfcko4qme4cko4swib
 * @url element://model:project::SAAMS/design:node:::id15rnfcko4qme4cko4swib.node107
 * @url element://model:project::SAAMS/design:view:::id3y5z3cko4qme4cko4sw81
 */
public class RefuellingSupervisor extends JFrame
        implements ActionListener {

  private final AircraftManagementDatabase aircraftManagementDatabase;
/**
  * The Refuelling Supervisor Screen interface has access to the AircraftManagementDatabase.
  * @supplierCardinality 1
  * @clientCardinality 1
  * @label accesses/observes
  * @directed*/
 // private AircraftManagementDatabase lnkUnnamed;
  private JButton showStatus;
  private JButton update;
  private JButton quit;

  public RefuellingSupervisor(AircraftManagementDatabase aircraftManagementDatabase,String title, int locationX, int locationY) {
    this.aircraftManagementDatabase = aircraftManagementDatabase;

    setTitle("Controller4");
    setLocation(locationX, locationY);
    setSize(350,150);
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    Container window = getContentPane();
    window.setLayout(new FlowLayout());


    update = new JButton("Update");
    window.add(update);
    update.addActionListener(this);


    // show status button
    showStatus = new JButton("Status");
    window.add(showStatus);
    showStatus.addActionListener(this);

    //quit button
    quit = new JButton("Quit");
    window.add(quit);
    quit.addActionListener(this);


    setVisible(true);
  }


  @Override
  public void actionPerformed(ActionEvent e) {
    if (e.getSource() == showStatus)

      if (e.getSource() == update)

        if (e.getSource() == quit)
          System.exit(0);

  }
}
